### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by havardAasen** [coin-or-tools/Data-Sample#2]
As it stands, it is difficult to know which license this project uses, one of the few files that is not autogenerated and has a copyright header is  _Makefile.am_, and reading that, it seems that either `EPL-1.0` or `EPL-2.0` is the correct one.

Would you be kind to add a LICENSE file to this project?

I can provide a pr if you want.

**Comment by svigerske** [comment]
Similar problem as in coin-or-tools/Data-Netlib#2: The license terms for the instances are not exactly clear. Even worse, I couldn't even say where they all origin from.

**Comment by tkralphs** [comment]
But I guess that the license for the instances is a completely separate issue from the license for this project itself. The whole purpose of the third-party mechanism is so that we aren't re-distributing the data files themselves.

**Comment by havardAasen** [comment]
> But I guess that the license for the instances is a completely separate issue from the license for this project itself. The whole purpose of the third-party mechanism is so that we aren't re-distributing the data files themselves.
> 

Are you saying that you believe all files in this repository should
retain the same license as the other COIN-OR projects?

**Comment by tkralphs** [comment]
>Are you saying that you believe all files in this repository should retain the same license as the other COIN-OR projects?

Hmm, no, I'm a little confused about how what I said gave that impression. What I meant was that this repo only contains a script for download and a simple wrapper that installs the instance files after they are downloaded. It does not contain the instances themselves. When you run the script, you are personally downloading them, so you assume the responsibility of ensuring that the instances are licensed in a way that is acceptable for you. In some cases, the license really isn't clear and that may not be OK for some people. That is part of the reason we choose not to redistribute the instances ourselves. The license in this repository only covers the script itself and the wrapper, which may not be what you're concerned about.

**Comment by havardAasen** [comment]
Thanks for the explanation, though I can't say it is completely clear to
me.
I would consider the *.mps files as the *instance files* that this repo
contains. It shouldn't be any difference if you clone the repo or download
them through a script.

Regardless, I was in the process of packaging these files for Debian
when the issue of the license arose.
Previously these files was included in CoinUtils, at least the way we
got hold of the source files, and everyone thought that the files had
the same license as the rest of the project. If that's no longer the
case, I'm not sure we can ship these files.

**Comment by tkralphs** [comment]
Oh sorry, I was not paying enough attention and I am completely wrong in what I said. We have other repos that function the way I described and I had my wires crossed. You are right, this one actually does contain the data. And @svigerske (who didn't correct my stupidity) is also right, it is unclear what the provenance of these instances is. They are instances that have been in wide circulation for a long time, so we felt confident taking the risk of distributing them. None of these are needed by end users, though, they are here to make it convenient to do testing. I don't see any reason they need to be packaged and distributed by Debian in case the provenance is an issue.

**Comment by havardAasen** [comment]
> Oh sorry, I was not paying enough attention and I am completely wrong in what I said. We have other repos that function the way I described and I had my wires crossed. You are right, this one actually does contain the data. And @svigerske <https://github.com/svigerske> (who didn't correct my stupidity) is also right, it is unclear what the provenance of these instances is. They are instances that have been in wide circulation for a long time, so we felt confident taking the risk of distributing them. None of these are needed by end users, though, they are here to make it convenient to do testing. I don't see any reason they need to be packaged and distributed by Debian in case the provenance is an issue.
> 

Thanks for the clarification, makes more sense to me now.
I was hoping to use these files for some more extensive testing of the
COIN-OR packages during build process. However, we'll proceed by
utilizing the unit tests incorporated within each project.
